#!/usr/bin/python3

player = {
    'name': 'Lionel Messi',
    'age': 30,
    'team': 'Barcelona',
    'position': 'forward'
}

print(player['position'])

def makePlayer(name, age, **dict):
    player = {}
    player['name'] = name
    player['age'] = age
    for k,v in dict.items():
        player[k] = v
    return player

def findPlayer(name, players):
    for player in players:
        if player['name'] == name:
            return True
        else:
            return False
players = [
    {'name': 'messi','club': 'barcelone'},
    {'name': 'maradona','club': 'napoli'},
    {'name': 'pele','club': 'santos'}
]

print(findPlayer('messi', players))
#print(makePlayer('messi',30,job = 'footballer', club = 'Barcelona'))
